from __future__ import annotations

PLACEHOLDER_LABELS = {
    "BINARY_PATH": "程序路径",
    "LIBC_PATH": "libc路径",
    "HOST": "远程地址",
    "PORT": "端口",
    "OFFSET": "溢出偏移",
    "WRITE_SIZE": "写入粒度",
    "NUMBWRITTEN": "已输出字节数",
    "VALUE_VAR": "写入值变量",
    "PROMPT": "等待提示",
    "IO_NAME": "IO 变量名",
    "PATTERN_LEN": "cyclic长度",
    "CRASH_VALUE": "崩溃值",
    "RET_GADGET": "ret地址",
    "WIN_SYMBOL": "win函数名",
    "POP_RDI": "pop rdi地址",
    "ADDR": "地址",
    "ADDR1": "地址1",
    "ADDR2": "地址2",
    "DATA": "发送数据",
    "BREAKPOINT": "断点地址",
    "FLAG_PATH": "flag路径",
    "START": "起始位置",
    "NEXT": "下一个位置",
    "NEXT2": "第三个位置",
    "END": "结束位置",
    "FMT_OFFSET": "格式化偏移",
    "TARGET_ADDR": "目标地址",
    "TARGET_VALUE": "目标值",
    "TARGET_FUNC_ADDR": "目标函数地址",
    "GOT_ADDR": "GOT地址",
    "SYSTEM_ADDR": "system地址",
    "BINSH_ADDR": "/bin/sh地址",
    "RETURN_ADDR": "返回地址",
    "RECV_LEN": "接收长度",
    "CANARY_POS": "canary位置",
    "PADDING_LEN": "填充长度",
    "SAVED_REG_LEN": "保存寄存器长度",
    "REQUEST_SIZE": "申请大小",
    "CHUNK_A_INDEX": "chunk A 索引",
    "CHUNK_B_INDEX": "chunk B 索引",
    "WRITE_VALUE": "写入值",
    "ONE_GADGET_OFFSET": "one_gadget偏移",
    "MAIN_ARENA_OFFSET": "main_arena偏移",
    "FD_STORAGE_ADDR": "fd保存位置地址",
    "FINAL_PAYLOAD": "最终payload",
    "PTR_ARRAY_ADDR": "指针数组地址",
    "FAKE_CHUNK_ADDR": "伪造chunk地址",
    "CHUNK_SIZE": "chunk大小",
    "TOP_CHUNK_ADDR": "top chunk地址",
    "SETCONTEXT_OFFSET": "setcontext偏移",
    "ROP_ADDR": "ROP地址",
    "RET_ADDR": "ret地址",
}


