server.document-root = "/home/ctf/www"
server.port = 8088

index-file.names = ( "index.html", "index.htm", "default.htm", "default.html" )

mimetype.assign = (
  ".html" => "text/html",
  ".txt" => "text/plain",
  ".jpg" => "image/jpeg",
  ".png" => "image/png"
)


# server.modules-dir = "/home/ctf/lib"


server.modules = (
  "mod_auth",
  "mod_authn_file",
)

server.modules += ( "mod_cgi" , "mod_access")

cgi.assign = ( ".cgi" => "/home/ctf/www/auth/main.cgi" )


auth.backend = "htpasswd"
auth.backend.htpasswd.userfile = "/home/ctf/www/authKey"
$HTTP["url"] =~ "^/authKey$" {
    url.access-deny = ("")
}


auth.require = ( "/auth/" =>
  (
    "method"  => "basic",
    "realm"   => "Login Frist",
    "require" => "user=admin"
  ),
)



