from __future__ import annotations

WSL_COMMAND_TEMPLATES = [
    {
        "title": "checksec 保护检测",
        "description": "查看 NX / Canary / PIE / RELRO，当前 WSL 已有 checksec。",
        "template": "checksec --file={{BINARY_PATH}}",
    },
    {
        "title": "file 架构识别",
        "description": "确认 ELF 位数、架构、动态/静态链接。",
        "template": "file {{BINARY_PATH}}",
    },
    {
        "title": "readelf 头部",
        "description": "查看 ELF Header、入口点、类型和架构。",
        "template": "readelf -h {{BINARY_PATH}}",
    },
    {
        "title": "readelf 符号表",
        "description": "查 main / puts / system 等符号。",
        "template": "readelf -s {{BINARY_PATH}} | grep -E \"main|puts|printf|system|read|write\"",
    },
    {
        "title": "readelf RELRO/fini",
        "description": "查 RELRO、fini_array 等常见利用相关段。",
        "template": "readelf -a {{BINARY_PATH}} | grep -E \"RELRO|fini|INIT|JMPREL|SYMTAB|STRTAB\"",
    },
    {
        "title": "objdump 反汇编",
        "description": "Intel 风格反汇编，适合快速看 main / vuln 周边。",
        "template": "objdump -d -M intel {{BINARY_PATH}} | less",
    },
    {
        "title": "objdump 搜 syscall",
        "description": "快速看 binary 里是否有 syscall gadget。",
        "template": "objdump -d {{BINARY_PATH}} | grep syscall",
    },
    {
        "title": "objdump GOT/重定位",
        "description": "快速看 GOT 重定位项，辅助 fmt GOT 覆盖。",
        "template": "objdump -R {{BINARY_PATH}}",
    },
    {
        "title": "ROPgadget 搜 gadget",
        "description": "当前 WSL 已有 ROPgadget。",
        "template": "ROPgadget --binary {{BINARY_PATH}} | grep -E \"pop|ret|syscall\"",
    },
    {
        "title": "ropper 搜 gadget",
        "description": "当前 WSL 已有 ropper。",
        "template": "ropper -f {{BINARY_PATH}} --search \"pop rdi; ret\"",
    },
    {
        "title": "one_gadget libc",
        "description": "当前 WSL 已有 one_gadget。",
        "template": "one_gadget {{LIBC_PATH}}",
    },
    {
        "title": "strings 查 /bin/sh",
        "description": "快速查 binary/libc 里的 /bin/sh 或 flag 字符串。",
        "template": "strings -a -t x {{BINARY_PATH}} | grep -E \"/bin/sh|flag\"",
    },
    {
        "title": "seccomp 沙箱检测",
        "description": "当前 WSL 已有 seccomp-tools，用来 dump syscall 规则。",
        "template": "seccomp-tools dump {{BINARY_PATH}}",
    },
    {
        "title": "seccomp 运行态 dump",
        "description": "适合程序运行后再安装 seccomp 的情况。",
        "template": "seccomp-tools dump {{BINARY_PATH}} -- {{BINARY_PATH}}",
    },
    {
        "title": "seccomp 带 ld/libc 检测",
        "description": "适合需要指定 ld.so 和 library-path 的本地题。",
        "template": "seccomp-tools dump -- {{LD_PATH}} --library-path {{RPATH}} {{BINARY_PATH}}",
    },
    {
        "title": "seccomp 编译规则",
        "description": "把 seccomp-tools asm 规则编译成 bpf 文件。",
        "template": "seccomp-tools asm sandbox.asm -o sandbox.bpf",
    },
    {
        "title": "seccomp 反汇编规则",
        "description": "把 bpf 规则文件反汇编成可读形式。",
        "template": "seccomp-tools disasm {{BPF_PATH}}",
    },
    {
        "title": "patchelf 查看解释器",
        "description": "只查看当前 interpreter，不修改文件。",
        "template": "patchelf --print-interpreter {{BINARY_PATH}}",
    },
    {
        "title": "patchelf 查看 rpath",
        "description": "只查看当前 rpath，不修改文件。",
        "template": "patchelf --print-rpath {{BINARY_PATH}}",
    },
    {
        "title": "patchelf 查看 needed",
        "description": "查看动态依赖名，常用于确认 libc.so.6。",
        "template": "patchelf --print-needed {{BINARY_PATH}}",
    },
    {
        "title": "patchelf 设置 ld/rpath",
        "description": "只复制命令，不在软件内自动执行；需要你确认路径后手动跑。",
        "template": "cp {{BINARY_PATH}} {{BINARY_PATH}}.bak && patchelf --set-interpreter {{LD_PATH}} --set-rpath {{RPATH}} {{BINARY_PATH}}",
    },
    {
        "title": "patchelf 替换 libc",
        "description": "替换 needed 里的 libc.so.6 为当前目录 libc。",
        "template": "patchelf --replace-needed libc.so.6 {{LIBC_PATH}} {{BINARY_PATH}}",
    },
    {
        "title": "LD_PRELOAD 运行提示",
        "description": "不用修改 ELF，临时挂指定 libc 运行。",
        "template": "LD_PRELOAD={{LIBC_PATH}} {{BINARY_PATH}}",
    },
    {
        "title": "pwninit 命令提示",
        "description": "如果 WSL 装了 pwninit，可自动生成 patched binary。",
        "template": "pwninit --bin {{BINARY_PATH}} --libc {{LIBC_PATH}}",
    },
    {
        "title": "gdb 启动",
        "description": "当前 WSL 已有 gdb/pwndbg，直接启动目标。",
        "template": "gdb -q {{BINARY_PATH}}",
    },
]


GDB_COMMAND_TEMPLATES = [
    ("设置 Intel 汇编", "set disassembly-flavor intel"),
    ("关闭分页", "set pagination off"),
    ("启动到入口", "start"),
    ("运行程序", "run"),
    ("断 main", "b *main"),
    ("断指定地址", "b *{{BREAKPOINT}}"),
    ("临时断点", "tb *{{BREAKPOINT}}"),
    ("查看断点", "info b"),
    ("继续运行", "c"),
    ("单步进入", "si"),
    ("单步跳过", "ni"),
    ("运行到函数返回", "finish"),
    ("运行到地址", "until *{{BREAKPOINT}}"),
    ("查看寄存器", "info registers"),
    ("pwndbg 上下文", "context"),
    ("栈 telescope", "telescope $rsp 20"),
    ("32位栈 telescope", "telescope $esp 20"),
    ("查看 rsp 内存", "x/20gx $rsp"),
    ("查看 esp 内存", "x/20wx $esp"),
    ("查看 rax 字节", "x/40bx $rax"),
    ("查看 rdi 字符串", "x/s $rdi"),
    ("反汇编 main", "disassemble main"),
    ("vmmap", "vmmap"),
    ("info proc mappings", "info proc mappings"),
    ("PIE 基址", "piebase"),
    ("libc 基址", "libcbase"),
    ("查 /bin/sh", "find /bin/sh"),
    ("搜 syscall 字节", "search -t bytes 0f05"),
    ("搜 FSOP 标志", "search -x 0xfbad1800"),
    ("GOT", "got"),
    ("PLT", "plt"),
    ("heap", "heap"),
    ("堆 bins", "bins"),
    ("fastbin", "fastbins"),
    ("smallbin", "smallbins"),
    ("largebin", "largebins"),
    ("arena", "arena"),
    ("tcache", "tcachebins"),
    ("heap chunks", "vis_heap_chunks"),
    ("canary", "canary"),
    ("cyclic 生成", "cyclic 200"),
    ("cyclic 查偏移", "cyclic -l {{CRASH_VALUE}}"),
    ("跟随子进程", "set follow-fork-mode child"),
    ("不分离 fork", "set detach-on-fork off"),
    ("捕获 fork", "catch fork"),
    ("seccomp syscall 断点", "catch syscall"),
    ("捕获 openat", "catch syscall openat"),
]

